### ISSUE TITLE
 Issue with    domain-4-system-hardening/kubeadm-calico.md  |  Step 6 - Install Network Addon (Calico):

### ISSUE THREAD

**Issue by nandha-coder** [zealvora/certified-kubernetes-security-specialist#25]
Network plugin URLs are not working.

kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml

Please replace it with below

kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.4/manifests/tigera-operator.yaml
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.4/manifests/custom-resources.yaml

**Comment by zealvora** [comment]
Thanks for reporting the issue, Nandha.

We have fixed our GitHub page with the above feedback along with few other changes to ensure things are working as expected.

**Comment by zealvora** [comment]
Closing this issue as it is now fixed.
